# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Gagauz spellchecker"
gag = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Gagauz, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
gag = "TRANSLATE: A spellchecker for Gagauz, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.gag"

[windows]
system_product_code = "{CEF28534-5F97-4C71-ACE3-94FE40036BAA}_is1"

[package.speller]
name = "Gagauz"
version = "0.1.0"

[package.grammar]
name = "Gagauz"
version = "0.1.0"

[package.tts-textproc]
name = "Gagauz"
version = "0.1.0"

[package.hyphenator]
name = "Gagauz"
version = "0.1.0"
